# Site settings
title: Summer School on modeling and complex systems 2023
email: angel.marchev@feb.uni-sofia.bg
description: >- # this means to ignore newlines until "baseurl:"
Organized by FEBA Faculty of Economics and Business Administration, 
FDIBA German Engineering and Industrial Management Faculty, 
University for National and World Economy
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marchev-science.github.io/Summer.School.2023/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: marchev-games
github_username:  angel-marchev

# Build settings
markdown: kramdown
theme: jekyll-theme-leap-day
plugins:
  - jekyll-feed
show_downloads: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
#  - Gemfile
#  - Gemfile.lock
#  - node_modules
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/

# If you want to use GitHub Pages, remove the "theme" directive above and
# uncomment the following line:
# remote_theme: owner/name
