markdown: kramdown
theme: jekyll-theme-leap-day
title: Summer School on modeling and complex systems 2023 
description: Organized by FEBA Faculty of Economics and Business Administration, FDIBA German Engineering and Industrial Management Faculty, University for National and World Economy
show_downloads: "false"
